version: "3.3"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB}
    volumes:
      - ./server/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    environment:
      APP_ENV: ${APP_ENV}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      DB: ${DB}
      HOST: ${HOST}
      PORT: ${PORT}
    restart: always
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    command: npm run start
